name: expenses
version: 0.0.1
summary: Expenses Tracker
description: Take control for your expenses!

confinement: strict
base: core18
grade: stable

slots:
  dbus-expenses: 
    interface: dbus
    bus: session
    name: tech.dzolotov.expenses
    
apps:
  expenses:
    command: expenses
    extensions: [flutter-master] # 
    plugs:
    - network
    slots:
      - dbus-expenses
parts:
  expenses:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

